<?php
    $nao_terminais = [
        '<PROGRAMA>' => '53',
        '<BLOCO>' => '54',
        '<DCLPROC>' => '55',
        '<DCLCONST>' => '56',
        '<DCLVAR>' => '57',
        '<CORPO>' => '58',
        '<TIPO>' => '59',
        '<LDCONST>' => '60',
        '<LID>' => '61',
        '<LDVAR>' => '62',
        '<REPIDENT>' => '63',
        '<TIPOARRAY>' => '64',
        '<DEFPAR>' => '65',
        '<COMANDO>' => '66',
        '<REPCOMANDO>' => '67',
        '<EXPRESSAO>' => '68',
        '<ELSEPARTE>' => '69',
        '<VARIAVEL>' => '70',
        '<REPVARIAVEL>' => '71',
        '<PARAMETROS>' => '72',
        '<ITEMSAIDA>' => '73',
        '<REPITEM>' => '74',
        '<TERMO>' => '75',
        '<REPEXP>' => '76',
        '<REPEXPSIMP>' => '77',
        '<FATOR>' => '78',
        '<REPTERMO>' => '79',
        '<EXPSIMP>' => '80'
    ];
?>